{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "radical-personality",
   "metadata": {},
   "outputs": [],
   "source": [
    "pragma solidity ^0.5.0;\n",
    "\n",
    "import \"./PupperCoin.sol\";\n",
    "import \"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/crowdsale/Crowdsale.sol\";\n",
    "import \"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/crowdsale/emission/MintedCrowdsale.sol\";\n",
    "import \"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/crowdsale/validation/CappedCrowdsale.sol\";\n",
    "import \"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/crowdsale/validation/TimedCrowdsale.sol\";\n",
    "import \"https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v2.5.0/contracts/crowdsale/distribution/RefundablePostDeliveryCrowdsale.sol\";\n",
    "\n",
    "// @TODO: Inherit the crowdsale contracts\n",
    "contract PupperCoinSale is Crowdsale, MintedCrowdsale, CappedCrowdsale, TimedCrowdsale, RefundableCrowdsale, RefundablePostDeliveryCrowdsale {\n",
    "\n",
    "    constructor(\n",
    "        // @TODO: Fill in the constructor parameters!\n",
    "        uint rate, // rate in TKNbits\n",
    "        address payable wallet, // sale beneficiary\n",
    "        PupperCoin token, // the PupperCoin itself that the PupperCoinSale will work with\n",
    "        uint goal,\n",
    "        uint cap,\n",
    "        uint OpenTime,\n",
    "        uint CloseTime\n",
    "\n",
    "    )\n",
    "        // @TODO: Pass the constructor parameters to the crowdsale contracts.\n",
    "        Crowdsale(rate, wallet, token)\n",
    "        MintedCrowdsale()\n",
    "        CappedCrowdsale(goal)\n",
    "        TimedCrowdsale(OpenTime, CloseTime)\n",
    "        RefundableCrowdsale(goal)\n",
    "        RefundablePostDeliveryCrowdsale()\n",
    "        public\n",
    "\n",
    "    {\n",
    "        // constructor can stay empty\n",
    "    }\n",
    "}\n",
    "\n",
    "contract PupperCoinSaleDeployer {\n",
    "\n",
    "    address public token_sale_address;\n",
    "    address public token_address;\n",
    "\n",
    "    constructor(\n",
    "        // @TODO: Fill in the constructor parameters!\n",
    "        string memory name,\n",
    "        string memory symbol,\n",
    "        address payable wallet // this address will receive all Ether raised by the sale\n",
    "\n",
    "    )\n",
    "        public\n",
    "    {\n",
    "        // @TODO: create the PupperCoin and keep its address handy\n",
    "        PupperCoin token = new PupperCoin(name, symbol, 0);\n",
    "        token_address = address(token);\n",
    "\n",
    "\n",
    "        // @TODO: create the PupperCoinSale and tell it about the token, set the goal, and set the open and close times to now and now + 24 weeks.\n",
    "        uint goal = 300 wei;\n",
    "        uint cap = 300 wei;\n",
    "        \n",
    "        \n",
    "        PupperCoinSale pupper_sale = new PupperCoinSale(1, wallet, token, goal, cap, now, now + 24 weeks);\n",
    "        token_sale_address = address(pupper_sale);\n",
    "\n",
    "\n",
    "        // make the PupperCoinSale contract a minter, then have the PupperCoinSaleDeployer renounce its minter role\n",
    "        token.addMinter(token_sale_address);\n",
    "        token.renounceMinter();\n",
    "    }\n",
    "}\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
